services:
  - type: web
    name: piclstats
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PICLSTATS_DATABASE_URL
        sync: false
      - key: PICLSTATS_LOG_LEVEL
        value: INFO
      - key: PICLSTATS_SCRAPE_DELAY_SECONDS
        value: "1.5"
